### ISSUE TITLE
This is great. However, there is a little bug with regards to the articles count. The count is less by one the actual number of articles. Please verify whether it s the case with all other users.

### ISSUE THREAD

**Issue by gitau-kinuthia** [andela/ah-jumanji-frontend#55]
This is great. However, there is a little bug with regards to the articles count. The count is less by one the actual number of articles. Please verify whether it s the case with all other users.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/20369585/52399796-59d0da80-2ace-11e9-90f7-29b4369f13dc.png">

_Originally posted by @fgkinus in https://github.com/andela/ah-jumanji-frontend/pull/54#issuecomment-461333886_

**Comment by GransonO** [comment]
Thank you for noticing that. 
This has been resolved.
